### ISSUE TITLE
Upgrade to Processing 4 (4.0.1)

### ISSUE THREAD

**Issue by hoh** [flathub/org.processing.processingide#9]
[Ben Fry announced](https://github.com/processing/processing4/blob/main/build/shared/revisions.md#processing-40) the final release of Processing 4.0 (revision 1285) a few months ago.

This repository is still for version 3.5.4

https://medium.com/@ProcessingOrg/announcing-the-latest-version-of-processing-processing-4-3a1f8b8a7aed

**Comment by Zishan-Rahman** [comment]
We can close this issue now (it should've been closed already) :+1:
